const menu=[
 {n:'Chicken Chargha Roll',c:'Rolls',p:299,e:'🌯',d:'Smoky chargha chicken'}, {n:'Malai Boti',c:'BBQ',p:299,e:'🍢',d:'Creamy charcoal grilled'}, {n:'Zinger Burger',c:'Burgers',p:400,e:'🍔',d:'Crispy chicken fillet'}, {n:'Chicken Paratha',c:'Paratha',p:299,e:'🫓',d:'Fresh tawa paratha'}, {n:'Special Shawarma',c:'Shawarma',p:549,e:'🥙',d:'Loaded chicken shawarma'}, {n:'Bihari Boti',c:'BBQ',p:299,e:'🍖',d:'Spiced tender beef'}, {n:'Mighty Tower Burger',c:'Burgers',p:650,e:'🍔',d:'Double stacked burger'}, {n:'Aloo Cheese Paratha',c:'Paratha',p:280,e:'🧀',d:'Cheesy stuffed paratha'}, {n:'Crunchy Wrap',c:'Rolls',p:449,e:'🌮',d:'Crunchy chicken wrap'}, {n:'Mint Margarita',c:'Drinks',p:200,e:'🍹',d:'Fresh mint cooler'}, {n:'Karak Chai',c:'Drinks',p:150,e:'☕',d:'Traditional tea'}, {n:'Chicken Nuggets',c:'Fried & Fries',p:650,e:'🍗',d:'Golden crispy bites'}
];
let cart=[], selectedCategory='All';
const money=n=>'₨ '+n.toLocaleString('en-PK');
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function renderMenu(){const query=document.querySelector('#menuSearch')?.value.toLowerCase()||'';const list=menu.filter(x=>(selectedCategory==='All'||x.c===selectedCategory)&&(x.n.toLowerCase().includes(query)));document.querySelector('#posMenu').innerHTML=list.map((x,i)=>`<article class="product" data-index="${menu.indexOf(x)}"><div class="product-art">${x.e}</div><b>${x.n}</b><small>${x.d}</small><strong>${money(x.p)}</strong><button class="add-circle">+</button></article>`).join('')||'<p>No menu items found.</p>'}
function renderCart(){let subtotal=cart.reduce((s,x)=>s+x.p*x.q,0),fee=Math.round(subtotal*.05),total=subtotal+fee;document.querySelector('#subtotal').textContent=money(subtotal);document.querySelector('#service').textContent=money(fee);document.querySelector('#total').textContent=money(total);document.querySelector('#payButton').innerHTML=`Charge ${money(total)} <span>→</span>`;document.querySelector('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div><b>${x.n}</b><small>${money(x.p)} each</small><div class="qty"><button data-q="-" data-i="${i}">−</button><span>${x.q}</span><button data-q="+" data-i="${i}">+</button></div></div><strong>${money(x.p*x.q)}</strong></div>`).join(''):'<div class="empty-cart">Your order is empty.<br><span>Tap a menu item to add it.</span></div>'}
function addToCart(item){let found=cart.find(x=>x.n===item.n);if(found)found.q++;else cart.push({...item,q:1});renderCart();showToast(`${item.n} added to the order`)}
document.querySelector('#posMenu').addEventListener('click',e=>{let card=e.target.closest('.product');if(card)addToCart(menu[card.dataset.index])});
document.querySelector('#cartItems').addEventListener('click',e=>{if(!e.target.dataset.q)return;let i=+e.target.dataset.i;cart[i].q+=e.target.dataset.q==='+'?1:-1;if(cart[i].q<1)cart.splice(i,1);renderCart()});
document.querySelector('#menuSearch').addEventListener('input',renderMenu);document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedCategory=b.dataset.category;renderMenu()});
document.querySelector('#clearCart').onclick=()=>{cart=[];renderCart();showToast('Order cleared')};document.querySelectorAll('.pay-mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.pay-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.querySelector('#payButton').onclick=()=>{if(!cart.length)return showToast('Add items before taking payment');let total=document.querySelector('#total').textContent;openModal(`<h2>Payment complete</h2><p>Your order has been sent to the kitchen and inventory has been updated.</p><div class="receipt"><b>Punjabi Dera</b><br>Order #PD-${Math.floor(1000+Math.random()*8999)}<br>${cart.length} item type(s) · Walk-in<br><strong>Total paid: ${total}</strong></div><button class="gold-btn" onclick="closeModal()">Done</button>`);cart=[];renderCart()};
function navTo(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector('#'+view).classList.add('active');document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===view));let titles={dashboard:'Good afternoon, Ahsan',pos:'Point of Sale',orders:'Live orders',inventory:'Inventory control',qr:'QR table ordering',menu:'Menu manager',reviews:'Guest ratings'};document.querySelector('#pageTitle').textContent=titles[view];window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>navTo(b.dataset.view));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>navTo(b.dataset.open));
const recent=[['PD-1082','Table 04','2 min ago','₨ 1,247','Preparing'],['PD-1081','QR · Table 06','5 min ago','₨ 899','New'],['PD-1080','Walk-in','8 min ago','₨ 2,099','Ready'],['PD-1079','Table 02','11 min ago','₨ 749','Preparing']];
document.querySelector('#recentOrders').innerHTML=recent.map((x,i)=>`<div class="recent-row"><span class="initials">${x[0].slice(-2)}</span><div><b>${x[0]} · ${x[1]}</b><small>${x[2]}</small></div><strong>${x[3]}</strong><span class="badge ${x[4]==='Ready'?'ready':''}">${x[4]}</span></div>`).join('');
const stocks=[['Chicken Breast','Meat & Poultry','3.2 kg','5 kg','₨ 850 / kg','critical'],['Cooking Oil','Pantry','4.5 L','5 L','₨ 620 / L','low'],['Tortilla Wraps','Bread & Bakery','18 pcs','20 pcs','₨ 32 / pc','low'],['Mint Leaves','Produce','0.6 kg','1 kg','₨ 120 / kg','critical'],['Cheddar Cheese','Dairy','4 kg','2 kg','₨ 1,420 / kg','good'],['Rice','Pantry','15 kg','5 kg','₨ 320 / kg','good']];
function stockHtml(data){return data.map((x,i)=>`<tr><td><b>${x[0]}</b><small>SKU-PD-${201+i}</small></td><td>${x[1]}</td><td class="stock-num">${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td><span class="status ${x[5]==='good'?'':x[5]}">${x[5]==='good'?'In stock':x[5]==='low'?'Low stock':'Critical'}</span></td><td class="dots">•••</td></tr>`).join('')};document.querySelector('#inventoryRows').innerHTML=stockHtml(stocks);document.querySelector('#stockSearch').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelector('#inventoryRows').innerHTML=stockHtml(stocks.filter(x=>x.join(' ').toLowerCase().includes(q)))};
document.querySelector('#stockAlerts').innerHTML=stocks.slice(0,4).map((x,i)=>`<div class="stock-row"><span class="${i===0||i===3?'red':''}"></span><div><b>${x[0]}</b><small>${x[2]} left · Reorder at ${x[3]}</small></div><div class="progress"><i style="width:${[31,45,52,22][i]}%"></i></div></div>`).join('');
const statuses={New:[['PD-1081','Table 06','Malai Boti, Karak Chai','5 min ago'],['PD-1083','QR · Table 08','Zinger Burger × 2, Fries','Just now']],Preparing:[['PD-1082','Table 04','Chicken Chargha Roll × 2, Mint Margarita','2 min ago'],['PD-1079','Table 02','Special Shawarma, Fries','11 min ago'],['PD-1077','Walk-in','Family Platter 1','14 min ago']],Ready:[['PD-1080','Walk-in','BBQ Platter 3, Drinks','8 min ago']]};
document.querySelector('#kanban').innerHTML=Object.entries(statuses).map(([name,orders])=>`<div class="kanban-col"><div class="kanban-title">${name}<span>${orders.length}</span></div>${orders.map(o=>`<article class="order-card"><div class="order-top"><b>${o[0]}</b><span>${o[1]}</span></div><small>${o[2]}</small><footer><span>${o[3]}</span>${name!=='Ready'?'<button class="advance">Advance →</button>':'<button class="advance">Complete ✓</button>'}</footer></article>`).join('')}</div>`).join('');document.querySelector('#kanban').onclick=e=>{if(e.target.classList.contains('advance')){e.target.closest('.order-card').style.opacity='.4';e.target.textContent='Updated ✓';showToast('Order status updated')}};
document.querySelector('#qrTables').innerHTML=Array.from({length:8},(_,i)=>`<article class="qr-card"><div class="fake-qr"></div><div><b>Table ${String(i+1).padStart(2,'0')}</b><small>punjabidera.pk/t/${i+1}</small><span>Download QR ↓</span></div></article>`).join('');document.querySelector('#qrTables').onclick=e=>{if(e.target.closest('.qr-card'))openModal('<h2>Table QR ready</h2><p>This QR links guests directly to the Punjabi Dera mobile menu for the selected table.</p><div class="receipt" style="text-align:center"><div class="fake-qr" style="margin:auto"></div><br><b>Table ordering · Punjabi Dera</b></div><button class="gold-btn" onclick="closeModal()">Download demo QR</button>')};
document.querySelector('#menuManager').innerHTML=menu.map(x=>`<article class="manager-item"><div class="product-art">${x.e}</div><div><b>${x.n}</b><small>${x.c}</small><strong>${money(x.p)}</strong></div><button onclick="showToast('Edit mode opened for ${x.n}')">•••</button></article>`).join('');
function openModal(html){document.querySelector('#modalContent').innerHTML=html;document.querySelector('#modal').classList.add('open')}function closeModal(){document.querySelector('#modal').classList.remove('open')}window.closeModal=closeModal;document.querySelector('.close-modal').onclick=closeModal;document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
document.querySelector('#addStock').onclick=()=>showToast('Demo: stock-item form would open here');document.querySelector('#addMenu').onclick=()=>showToast('Demo: menu-item form would open here');document.querySelector('#printQr').onclick=()=>{window.print();showToast('QR table sheet opened for printing')};
renderMenu();renderCart();
