const staffAccounts={
 'admin@punjabidera.pk':{password:'admin123',role:'admin',name:'Ahsan Ejaz',initials:'AE',label:'Administrator'},
 'cashier@punjabidera.pk':{password:'cashier123',role:'cashier',name:'Hina Raza',initials:'HR',label:'Cashier'},
 'kitchen@punjabidera.pk':{password:'kitchen123',role:'kitchen',name:'Bilal Khan',initials:'BK',label:'Kitchen staff'}
};
function setStaffSession(account){localStorage.setItem('pd-staff-session',JSON.stringify(account));applyStaffAccess(account)}
function applyStaffAccess(account){document.querySelector('#authScreen').classList.add('hidden');document.querySelector('#profileInitials').textContent=account.initials;document.querySelector('#currentRole').textContent=account.label;document.querySelector('#pageTitle').textContent=account.role==='kitchen'?'Kitchen order board':`Welcome, ${account.name.split(' ')[0]}`;document.querySelectorAll('.nav-link').forEach(button=>button.style.display=button.dataset.roles.includes(account.role)?'flex':'none');let start=account.role==='kitchen'?'orders':account.role==='cashier'?'pos':'dashboard';navTo(start);syncCustomerOrders()}
function syncCustomerOrders(){let incoming=JSON.parse(localStorage.getItem('pd-orders')||'[]');if(!incoming.length)return;let added=incoming.map(o=>[o.id,`QR · Table ${o.table}`,o.time,'Pending','New']);let container=document.querySelector('#recentOrders');if(container)container.insertAdjacentHTML('afterbegin',added.map(x=>`<div class="recent-row"><span class="initials">QR</span><div><b>${x[0]} · ${x[1]}</b><small>${x[2]}</small></div><strong>${x[3]}</strong><span class="badge">${x[4]}</span></div>`).join(''));document.querySelector('#orderBadge').textContent=6+incoming.length}
document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();let user=document.querySelector('#loginUser').value.trim().toLowerCase(),pass=document.querySelector('#loginPass').value;let account=staffAccounts[user];if(!account||account.password!==pass){document.querySelector('#authError').textContent='Incorrect staff ID or password. Please try again.';return}setStaffSession(account)});
document.querySelectorAll('.demo-login').forEach(button=>button.onclick=()=>{let account=staffAccounts[button.dataset.user];document.querySelector('#loginUser').value=button.dataset.user;document.querySelector('#loginPass').value=account.password;setStaffSession(account)});
document.querySelector('#logoutButton').onclick=()=>{localStorage.removeItem('pd-staff-session');document.querySelector('#authScreen').classList.remove('hidden');document.querySelector('#loginPass').value='';document.querySelector('#authError').textContent=''};
let saved=JSON.parse(localStorage.getItem('pd-staff-session')||'null');if(saved&&staffAccounts[saved.email||Object.keys(staffAccounts).find(k=>staffAccounts[k].role===saved.role)]){let match=Object.values(staffAccounts).find(x=>x.role===saved.role&&x.name===saved.name);if(match)applyStaffAccess(match)}
