/* Professional POS ledger demo. In production, these records belong in a database. */
const ledgerKey='pd-ledger-v1';
const seedLedger=[
 {at:'11:02 AM',ref:'PD-1077',account:'Cash on Hand',description:'Walk-in ticket payment',debit:4999,credit:0,method:'Cash'},
 {at:'11:02 AM',ref:'PD-1077',account:'Food Sales',description:'Family Platter 1',debit:0,credit:4761,method:'POS'},
 {at:'11:02 AM',ref:'PD-1077',account:'Service Charge Income',description:'5% service charge',debit:0,credit:238,method:'POS'},
 {at:'11:26 AM',ref:'PD-1080',account:'Card Clearing',description:'Walk-in ticket payment',debit:2099,credit:0,method:'Card'},
 {at:'11:26 AM',ref:'PD-1080',account:'Food Sales',description:'BBQ Platter 3',debit:0,credit:1999,method:'POS'},
 {at:'11:26 AM',ref:'PD-1080',account:'Service Charge Income',description:'5% service charge',debit:0,credit:100,method:'POS'}
];
function getLedger(){let saved=localStorage.getItem(ledgerKey);return saved?JSON.parse(saved):seedLedger}function saveLedger(entries){localStorage.setItem(ledgerKey,JSON.stringify(entries))}function lmoney(v){return v?`₨ ${Number(v).toLocaleString('en-PK')}`:'—'}
function renderLedger(){let entries=getLedger();let balances={cash:0,card:0,online:0,sales:0};entries.forEach(e=>{if(e.account==='Cash on Hand')balances.cash+=e.debit-e.credit;if(e.account==='Card Clearing')balances.card+=e.debit-e.credit;if(e.account==='Online Clearing')balances.online+=e.debit-e.credit;if(e.account==='Food Sales'||e.account==='Service Charge Income')balances.sales+=e.credit-e.debit});document.querySelector('#ledgerBalances').innerHTML=[['Cash on hand',balances.cash,'Ready to reconcile'],['Card clearing',balances.card,'Pending settlement'],['Online clearing',balances.online,'Pending settlement'],['Sales recognised',balances.sales,'Today’s revenue']].map(x=>`<article class="ledger-balance"><small>${x[0]}</small><strong>${lmoney(x[1])}</strong><span>${x[2]}</span></article>`).join('');document.querySelector('#ledgerRows').innerHTML=entries.slice().reverse().map(e=>`<tr><td><b>${e.at}</b><span class="ledger-ref">${e.ref}</span></td><td><b>${e.account}</b></td><td>${e.description}</td><td>${lmoney(e.debit)}</td><td>${lmoney(e.credit)}</td><td><span class="status ${e.method==='Cash'?'':'low'}">${e.method}</span></td></tr>`).join('')}
function recordSale(total,subtotal,payment,table){let orderId='PD-'+Math.floor(2000+Math.random()*7000), service=total-subtotal, account=payment==='Cash'?'Cash on Hand':payment==='Card'?'Card Clearing':'Online Clearing',now=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});let entries=getLedger();entries.push({at:now,ref:orderId,account,description:`${table} ticket payment`,debit:total,credit:0,method:payment},{at:now,ref:orderId,account:'Food Sales',description:`${table} menu items`,debit:0,credit:subtotal,method:'POS'},{at:now,ref:orderId,account:'Service Charge Income',description:'5% service charge',debit:0,credit:service,method:'POS'});saveLedger(entries);renderLedger();return orderId}
document.querySelector('#payButton').onclick=()=>{if(!cart.length)return showToast('Add items before taking payment');let subtotal=cart.reduce((s,x)=>s+x.p*x.q,0),total=subtotal+Math.round(subtotal*.05),payment=document.querySelector('.pay-mode.active').textContent,table=document.querySelector('#tableSelect').value,orderId=recordSale(total,subtotal,payment,table);openModal(`<h2>Payment complete</h2><p>Order and balanced ledger entries have been recorded.</p><div class="receipt"><b>Punjabi Dera</b><br>Order ${orderId}<br>${table} · ${payment}<br><strong>Total paid: ${lmoney(total)}</strong></div><button class="gold-btn" onclick="closeModal()">Done</button>`);cart=[];renderCart()};
document.querySelector('#cashDrop').onclick=()=>{let amount=prompt('Cash amount to transfer to bank deposit:');amount=Number(amount);if(!amount||amount<1)return;let now=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),ref='CD-'+Date.now().toString().slice(-5),entries=getLedger();entries.push({at:now,ref,account:'Bank Deposit',description:'Cash drop from till',debit:amount,credit:0,method:'Cash drop'},{at:now,ref,account:'Cash on Hand',description:'Cash drop to bank',debit:0,credit:amount,method:'Cash drop'});saveLedger(entries);renderLedger();showToast('Cash drop recorded in the ledger')};
document.querySelector('#exportLedger').onclick=()=>{let rows=[['Time','Reference','Account','Description','Debit','Credit','Method'],...getLedger().map(e=>[e.at,e.ref,e.account,e.description,e.debit,e.credit,e.method])],csv=rows.map(r=>r.map(v=>`"${v}"`).join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='punjabi-dera-pos-ledger.csv';a.click();URL.revokeObjectURL(a.href)};let priorNavTo=navTo;navTo=function(view){priorNavTo(view);if(view==='ledgers')document.querySelector('#pageTitle').textContent='POS ledgers'};renderLedger();
