/* Restaurant operations: tables, inventory, and printable POS receipts. Browser-storage demo. */
const inventoryKey='pd-inventory-v2',tableKey='pd-tables-v2';
const inventorySeed=[
 {id:1,name:'Chicken Breast',category:'Meat & Poultry',unit:'kg',onHand:3.2,reorder:5,cost:850},
 {id:2,name:'Cooking Oil',category:'Pantry',unit:'L',onHand:4.5,reorder:5,cost:620},
 {id:3,name:'Tortilla Wraps',category:'Bread & Bakery',unit:'pcs',onHand:18,reorder:20,cost:32},
 {id:4,name:'Mint Leaves',category:'Produce',unit:'kg',onHand:.6,reorder:1,cost:120},
 {id:5,name:'Cheddar Cheese',category:'Dairy',unit:'kg',onHand:4,reorder:2,cost:1420},
 {id:6,name:'Rice',category:'Pantry',unit:'kg',onHand:15,reorder:5,cost:320}
];
const tableSeed=Array.from({length:12},(_,i)=>({id:i+1,name:`Table ${String(i+1).padStart(2,'0')}`,seats:i<8?4:6,status:i===1?'occupied':i===4?'reserved':'available',area:i>9?'Family section':'Main dining'}));
const getInventory=()=>JSON.parse(localStorage.getItem(inventoryKey)||JSON.stringify(inventorySeed));const setInventory=x=>localStorage.setItem(inventoryKey,JSON.stringify(x));const getTables=()=>JSON.parse(localStorage.getItem(tableKey)||JSON.stringify(tableSeed));const setTables=x=>localStorage.setItem(tableKey,JSON.stringify(x));
function invStatus(item){let ratio=item.onHand/item.reorder;return ratio<=.5?'Critical':ratio<1?'Low stock':'In stock'}function renderInventory(){let data=getInventory();document.querySelector('#inventoryRows').innerHTML=data.map(x=>{let status=invStatus(x),klass=status==='In stock'?'':status==='Low stock'?'low':'critical';return `<tr><td><b>${x.name}</b><small>SKU-PD-${String(x.id).padStart(3,'0')}</small></td><td>${x.category}</td><td class="stock-num">${x.onHand} ${x.unit}</td><td>${x.reorder} ${x.unit}</td><td>₨ ${x.cost.toLocaleString()} / ${x.unit}</td><td><span class="status ${klass}">${status}</span></td><td><div class="inventory-actions"><button data-receive="${x.id}">Receive</button><button data-delete-stock="${x.id}">Delete</button></div></td></tr>`}).join('');}
function renderTables(){let tables=getTables(),counts={available:0,occupied:0,reserved:0};tables.forEach(t=>counts[t.status]++);document.querySelector('#floorSummary').innerHTML=[['Total tables',tables.length],['Available',counts.available],['Occupied',counts.occupied],['Reserved',counts.reserved]].map(x=>`<article class="floor-stat"><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('');document.querySelector('#tablesGrid').innerHTML=tables.map(t=>`<article class="floor-table ${t.status}"><b class="table-number">${t.name}</b><span class="table-meta">${t.seats} seats · ${t.area}</span><span class="table-state">${t.status[0].toUpperCase()+t.status.slice(1)}</span><div class="table-actions"><button data-table-state="${t.id}">Change status</button><button data-delete-table="${t.id}">Remove</button></div></article>`).join('');let select=document.querySelector('#tableSelect'),old=select.value;select.innerHTML='<option>Walk-in</option>'+tables.filter(t=>t.status!=='occupied').map(t=>`<option>${t.name}</option>`).join('');if([...select.options].some(x=>x.value===old))select.value=old;}
function openInventoryForm(){openModal(`<h2>Add inventory item</h2><p>Create an ingredient or supply item. It will be tracked in the inventory ledger.</p><form class="stock-form" id="stockForm"><label>Item name<input name="name" required placeholder="e.g. Chicken Breast"></label><label>Category<input name="category" required placeholder="e.g. Meat & Poultry"></label><label>Opening quantity<input type="number" min="0" step=".1" name="onHand" required></label><label>Unit<select name="unit"><option>kg</option><option>L</option><option>pcs</option><option>pack</option></select></label><label>Reorder at<input type="number" min="0" step=".1" name="reorder" required></label><label>Unit cost (PKR)<input type="number" min="0" name="cost" required></label><button class="modal-form-submit">Save inventory item</button></form>`);document.querySelector('#stockForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),items=getInventory();items.push({id:Date.now(),name:f.get('name'),category:f.get('category'),onHand:Number(f.get('onHand')),unit:f.get('unit'),reorder:Number(f.get('reorder')),cost:Number(f.get('cost'))});setInventory(items);renderInventory();closeModal();showToast('Inventory item created')};}
function receiveStock(id){let items=getInventory(),item=items.find(x=>x.id===id);openModal(`<h2>Receive stock</h2><p>Add received quantity for <b>${item.name}</b>. Current balance: ${item.onHand} ${item.unit}.</p><form class="stock-form" id="receiveForm"><label class="full">Quantity received<input type="number" min=".1" step=".1" name="quantity" required autofocus></label><label class="full">Supplier note (optional)<input name="note" placeholder="e.g. Gujrat Fresh Foods invoice #181"></label><button class="modal-form-submit">Post stock receipt</button></form>`);document.querySelector('#receiveForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),quantity=Number(f.get('quantity'));item.onHand+=quantity;setInventory(items);renderInventory();closeModal();showToast(`${quantity} ${item.unit} added to ${item.name}`)}}
function addTableForm(){openModal(`<h2>Add dining table</h2><p>Create a table that cashiers can select directly inside the POS.</p><form class="stock-form" id="tableForm"><label>Table name<input name="name" required placeholder="e.g. Table 13"></label><label>Seats<input type="number" name="seats" value="4" min="1" required></label><label class="full">Area<select name="area"><option>Main dining</option><option>Family section</option><option>Outdoor</option></select></label><button class="modal-form-submit">Add table</button></form>`);document.querySelector('#tableForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),tables=getTables();tables.push({id:Date.now(),name:f.get('name'),seats:Number(f.get('seats')),area:f.get('area'),status:'available'});setTables(tables);renderTables();closeModal();showToast('Table added to the floor plan')}}
document.querySelector('#addStock').onclick=openInventoryForm;document.querySelector('#inventoryRows').onclick=e=>{let id=Number(e.target.dataset.receive||e.target.dataset.deleteStock);if(!id)return;if(e.target.dataset.receive)return receiveStock(id);if(confirm('Remove this inventory item?')){setInventory(getInventory().filter(x=>x.id!==id));renderInventory();showToast('Inventory item removed')}};document.querySelector('#addTable').onclick=addTableForm;document.querySelector('#tablesGrid').onclick=e=>{let id=Number(e.target.dataset.tableState||e.target.dataset.deleteTable);if(!id)return;let tables=getTables(),t=tables.find(x=>x.id===id);if(e.target.dataset.deleteTable){if(confirm(`Remove ${t.name}?`)){setTables(tables.filter(x=>x.id!==id));renderTables();showToast('Table removed')}return}let next={available:'occupied',occupied:'reserved',reserved:'available'};t.status=next[t.status];setTables(tables);renderTables();showToast(`${t.name} marked ${t.status}`)};
let navBeforeRestaurant=navTo;navTo=function(view){navBeforeRestaurant(view);if(view==='tables')document.querySelector('#pageTitle').textContent='Table manager';if(view==='inventory')renderInventory();};
function printReceipt(){window.print()}window.printReceipt=printReceipt;document.querySelector('#payButton').onclick=()=>{if(!cart.length)return showToast('Add items before taking payment');let subtotal=cart.reduce((s,x)=>s+x.p*x.q,0),service=Math.round(subtotal*.05),total=subtotal+service,payment=document.querySelector('.pay-mode.active').textContent,table=document.querySelector('#tableSelect').value,orderId=recordSale(total,subtotal,payment,table),time=new Date().toLocaleString('en-PK',{dateStyle:'medium',timeStyle:'short'});let lines=cart.map(x=>`<div class="receipt-line"><span>${x.q} × ${x.n}</span><b>₨ ${(x.q*x.p).toLocaleString()}</b></div>`).join('');openModal(`<div class="print-receipt"><div class="receipt-brand"><h2>Punjabi Dera</h2><small>Sip, Swaad, Tay Sutta!</small><small>Punjabi Dera Opposite Qand Fishan Sweets<br>Bhimber Road, Gujrat · 03348622777</small></div><div class="receipt-lines"><div class="receipt-line"><span>Receipt</span><b>${orderId}</b></div><div class="receipt-line"><span>${time}</span><b>${table}</b></div></div><div class="receipt-lines">${lines}</div><div class="receipt-lines"><div class="receipt-line"><span>Subtotal</span><b>₨ ${subtotal.toLocaleString()}</b></div><div class="receipt-line"><span>Service charge (5%)</span><b>₨ ${service.toLocaleString()}</b></div><div class="receipt-line receipt-total"><span>Total</span><b>₨ ${total.toLocaleString()}</b></div><div class="receipt-line"><span>Payment method</span><b>${payment}</b></div></div><div class="receipt-footer">Thank you for dining with us!<br>Please visit again.</div></div><div class="receipt-actions"><button class="done" onclick="closeModal()">Done</button><button class="print" onclick="printReceipt()">Print receipt</button></div>`);cart=[];renderCart();showToast('Sale posted and receipt is ready')};
renderInventory();renderTables();
